version: '2'
services:
  e4i-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/e4i/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=e4i
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
