export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ARCHIVED = 'ROLE_ARCHIVED',
  COMPANY_ADMIN = 'ROLE_COMPANY_ADMIN',
  COMPANY_USER = 'ROLE_COMPANY_USER',
  CMS_ADMIN = 'ROLE_CMS_ADMIN',
}
